/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#131315",
        "surface-dim": "#131315",
        "surface-bright": "#39393b",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1c1b1d",
        "surface-container": "#201f21",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "surface-variant": "#353437",
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#c7c4d7",
        "inverse-surface": "#e5e1e4",
        "inverse-on-surface": "#313032",
        "outline": "#908fa0",
        "outline-variant": "#464554",
        "surface-tint": "#c0c1ff",
        "primary": "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "inverse-primary": "#494bd6",
        "secondary": "#c3c0ff",
        "on-secondary": "#1d00a5",
        "secondary-container": "#3626ce",
        "on-secondary-container": "#b3b1ff",
        "tertiary": "#4edea3",
        "on-tertiary": "#003824",
        "tertiary-container": "#00885d",
        "on-tertiary-container": "#000703",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "background": "#131315",
        "on-background": "#e5e1e4",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "secondary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#c3c0ff",
        "brand-indigo": "#6366F1",
        "brand-emerald": "#10B981"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-2": "0.125rem",
        "space-4": "0.25rem",
        "space-8": "0.5rem",
        "space-12": "0.75rem",
        "space-16": "1rem",
        "space-20": "1.25rem",
        "space-24": "1.5rem",
        "space-32": "2rem",
        "gutter-mobile": "0.75rem",
        "margin-mobile": "1rem",
        "bottom-nav-height": "3.5rem",
        "touch-target-min": "3rem"
      },
      fontFamily: {
        "headline-lg": ["'Space Grotesk'", "sans-serif"],
        "headline-md": ["'Space Grotesk'", "sans-serif"],
        "headline-sm": ["'Space Grotesk'", "sans-serif"],
        "label-lg": ["'Space Grotesk'", "sans-serif"],
        "label-md": ["'Space Grotesk'", "sans-serif"],
        "label-sm": ["'Space Grotesk'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "body-sm": ["'Inter'", "sans-serif"]
      }
    }
  },
  plugins: [],
}
